[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["joshua Aposgol <joshuaapostol909@gmail.com>"]
requires-python = ">=3.11"
dependencies = [
    "crypto>=1.4.1",
    "cryptography>=44.0.0",
    "pytz>=2024.2",
    "requests>=2.32.3",
]
